name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.epicquests.EpicQuests
depend:
  - Citizens
softdepend:
  - MythicMobs

author: Songoda
website: ${project.url}

commands:
  EpicQuests:
    description: Reloads the configuration file
    default: true
    aliases:
      - quest
    usage: /epicquests reload
